/**
 * RFC 7807 Problem Details for HTTP APIs
 * https://tools.ietf.org/html/rfc7807
 */
export interface ProblemDetails {
  /** A URI reference that identifies the problem type */
  type: string;
  
  /** A short, human-readable summary of the problem type */
  title: string;
  
  /** The HTTP status code generated by the origin server */
  status: number;
  
  /** A human-readable explanation specific to this occurrence */
  detail: string;
  
  /** A URI reference that identifies the specific occurrence */
  instance?: string;
  
  /** Extension members (additional problem-specific details) */
  [key: string]: any;
}

export interface ValidationProblemDetails extends ProblemDetails {
  errors: {
    field: string;
    message: string;
    rejectedValue?: any;
  }[];
}

export interface BusinessRuleViolationDetails extends ProblemDetails {
  rule: string;
  constraint: string;
  currentValue?: any;
  allowedValues?: any[];
}

export interface ConsentProblemDetails extends ProblemDetails {
  consentId?: string;
  missingPermissions?: string[];
  expiredAt?: Date;
}

export interface PaymentProblemDetails extends ProblemDetails {
  paymentId?: string;
  idempotencyKey?: string;
  failedStep?: string;
  sagaId?: string;
}